framework:
    workflows:
        ordering_workflow:
            type: 'workflow' # or 'state_machine'
            marking_store:
                type: 'single_state' # or 'multiple_state'
                arguments:
                    - 'status'
            supports:
                - App\Entity\Order
            initial_place: created
            places:
                - created
                - awaiting
                - validated
                - refused
                - shipped
                - delivered
                - failed
            transitions:
                to_restaurant:
                    from: created
                    to: awaiting
                processing:
                    from: awaiting
                    to: validated
                refusing:
                    from: awaiting
                    to: refused
                delivering:
                    from: validated
                    to: shipped
                completed:
                    from: shipped
                    to: delivered
                failing:
                    from: shipped
                    to: failed
